# Generated by Django 4.2.13 on 2024-07-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "branch_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("created_timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated_timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_timestamp"],},
        ),
        migrations.CreateModel(
            name="Files",
            fields=[
                ("url", models.URLField(primary_key=True, serialize=False)),
                ("meta_data", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "repo_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
                ("gc_bucket", models.URLField(default="")),
                (
                    "default_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch",
                        to="myapp.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Range",
            fields=[
                (
                    "range_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("files", models.ManyToManyField(to="myapp.files")),
            ],
        ),
        migrations.CreateModel(
            name="MetaRange",
            fields=[
                (
                    "meta_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("ranges", models.ManyToManyField(to="myapp.range")),
            ],
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "commit_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "meta_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.metarange",
                    ),
                ),
            ],
            options={"ordering": ["-timestamp"],},
        ),
        migrations.AddField(
            model_name="branch",
            name="commit_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commits",
                to="myapp.commit",
            ),
        ),
    ]
