# Generated by Django 4.2.13 on 2024-07-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users", old_name="name", new_name="username",
        ),
    ]
