# Generated by Django 4.2.13 on 2024-07-03 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_repo_gc_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="repo_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repo",
                to="myapp.repo",
            ),
        ),
        migrations.AddField(
            model_name="commit",
            name="add",
            field=models.ManyToManyField(
                default=[], related_name="add_set", to="myapp.files"
            ),
        ),
        migrations.AddField(
            model_name="commit",
            name="edit",
            field=models.ManyToManyField(
                default=[], related_name="edit_set", to="myapp.files"
            ),
        ),
        migrations.AddField(
            model_name="commit",
            name="remove",
            field=models.ManyToManyField(
                default=[], related_name="remove_set", to="myapp.files"
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="default_branch",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="repo",
            name="repo_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="usertorepo",
            name="repo_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repo_user",
                to="myapp.repo",
            ),
        ),
    ]
