# Generated by Django 4.2.13 on 2024-07-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_branch_repo_id_commit_add_commit_edit_commit_remove_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="repo_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repo",
                to="myapp.repo",
            ),
        ),
    ]
